package com.fr.spring.jdbc.dao.impl;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

import org.springframework.jdbc.core.PreparedStatementCreator;
import org.springframework.jdbc.core.support.JdbcDaoSupport;
import org.springframework.jdbc.support.GeneratedKeyHolder;
import org.springframework.jdbc.support.KeyHolder;

import com.fr.spring.jdbc.dao.AdminDao;
import com.fr.spring.jdbc.model.Admin;

public class AdminDaoJdbcSupportImpl  extends JdbcDaoSupport implements AdminDao{

	/*
	 * It will save the admin record and get the auto incremented id value from database.
	 */
	public void save(final Admin admin) {

		final String query = "insert into admin (name) values (?)";
		
		KeyHolder keyHolder = new GeneratedKeyHolder();
		getJdbcTemplate().update(new PreparedStatementCreator() {
			
			public PreparedStatement createPreparedStatement(Connection con) throws SQLException {
				
				PreparedStatement ps = con.prepareStatement(query,new String[] { "id "} );
				ps.setString(1, admin.getName());
				
				return ps;
			}
		},keyHolder);
		
		System.out.println("Autogenerated key admin key is ====>"+keyHolder.getKey());
	}

	
	
}
